/**
 * This file is autogenerated by Scaffold-ETH.
 * You should not edit it manually or your changes might be overwritten.
 */
import { GenericContractsDeclaration } from "~~/utils/scaffold-eth/contract";

const deployedContracts = {
  31337: {
    Groth16Verifier: {
      address: "0xb19b36b1456e65e3a6d514d3f715f204bd59f431",
      abi: [
        {
          type: "function",
          name: "verifyProof",
          inputs: [
            {
              name: "_pA",
              type: "uint256[2]",
              internalType: "uint256[2]",
            },
            {
              name: "_pB",
              type: "uint256[2][2]",
              internalType: "uint256[2][2]",
            },
            {
              name: "_pC",
              type: "uint256[2]",
              internalType: "uint256[2]",
            },
            {
              name: "_pubSignals",
              type: "uint256[1]",
              internalType: "uint256[1]",
            },
          ],
          outputs: [
            {
              name: "",
              type: "bool",
              internalType: "bool",
            },
          ],
          stateMutability: "view",
        },
      ],
      inheritedFunctions: {},
      deployedOnBlock: 3,
    },
  },
} as const;

export default deployedContracts satisfies GenericContractsDeclaration;
